[default]
#words
extend-ignore-words-re = [
  #Proper nouns

  #False positives
  "ba"

  #Exceptions
  #Cases where we want to respect the original text despite typos

]

#identifiers
extend-ignore-identifiers-re = []

#excluded files
[files]
extend-exclude = [".codespellrc"]